Add dummy SourceView, workaround Splitpane bug
Using (even a trivial) Splitpane in tests causes
"TypeError: ctx[11] is not a function".
We work around that by adding TrackerDetailSplit, which skips the
Splitpane in tests.